import type { Metadata } from 'next'
import { Inter , Oxygen, Noto_Sans} from 'next/font/google'
import './globals.css'
import Nav from './components/nav'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })
const oxygen = Oxygen({ weight: ["300","400","700"],style:["normal"], subsets: ["latin"] })
const notoSans = Noto_Sans ({ weight: ["100",'300',"400",'700'],style: ["normal"],subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Insightful',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      
      <body className={notoSans.className}>
        <div className='min-h-screen '>
        <Nav />

<div className='flex justify-center items-center h-screen sm:p-0 lg:p-16 bg-slate-50 dark:bg-gray-900'>
{children}
</div>

        </div>
      
        </body>
    </html>
    </ClerkProvider>
  )
}
